function(check_builtin source_file function_name)
    message(CHECK_START "Checking for " ${function_name})
    try_compile(CHECK_RESULT ${PROJECT_BINARY_DIR} SOURCES ${source_file} OUTPUT_VARIABLE CHECK_RESULT_OUT)
    if (${CHECK_RESULT})
        message(CHECK_PASS "found")
    else ()
        message(CHECK_FAIL "not found")
        list(APPEND CMAKE_MESSAGE_INDENT "  ")
        message(VERBOSE "Failed with output:\n" ${CHECK_RESULT_OUT})
        list(APPEND missingComponents ${function_name})
        set(missingComponents ${missingComponents} PARENT_SCOPE)
    endif ()
endfunction()
