set(CMAKE_SYSTEM_NAME Popcorn)
set(CMAKE_SYSTEM_PROCESSOR amd64)

set(triple x86_64-unknown-popcorn)

set(CMAKE_C_COMPILER ${CLANG_INSTALL}/bin/clang)
set(CMAKE_C_COMPILER_TARGET ${triple})
set(CMAKE_CXX_COMPILER ${CLANG_INSTALL}/bin/clang++)
set(CMAKE_CXX_COMPILER_TARGET ${triple})
set(CMAKE_SYSROOT ${CLANG_INSTALL})
set(CMAKE_ASM_NASM_OBJECT_FORMAT elf64)
set(CMAKE_ASM_NASM_FLAGS_DEBUG "-g -Fdwarf")

set(CMAKE_RANLIB ${CROSS_RANLIB})
set(CMAKE_AR ${CROSS_AR})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE NEVER)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

find_program(CMAKE_NM ${CLANG_INSTALL}/bin/llvm-nm)
find_program(CMAKE_AR ${CLANG_INSTALL}/bin/llvm-ar)
find_program(CMAKE_RANLIB ${CLANG_INSTALL}/bin/llvm-ranlib)
find_program(CMAKE_OBJCOPY ${CLANG_INSTALL}/bin/llvm-objcopy)
find_program(CMAKE_STRIP ${CLANG_INSTALL}/bin/llvm-strip)
